# VacationPy
---

## Starter Code to Import Libraries and Load the Weather and Coordinates Data

In [18]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os



# Import API key
from api_keys import geoapify_key

In [19]:
!jupyter nbextension enable --py gmaps

Enabling notebook extension jupyter-gmaps/extension...
      - Validating: ok

In [20]:
# Load the CSV file created in Part 1 into a Pandas DataFrame
city_data_df = pd.read_csv("output_data/cities.csv")

# Display sample data
city_data_df.head()

,City_ID,City,Lat,lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,jamestown,42.0970,-79.2353,81.01,55.0,40.0,13.00,US,1.689618e+09
1,1,bethel,41.3712,-73.4140,88.90,59.0,0.0,4.61,US,1.689618e+09
2,2,ayagoz,47.9714,80.4392,66.58,45.0,0.0,9.46,KZ,1.689618e+09
3,3,chapais,49.7834,-74.8492,65.98,50.0,26.0,12.95,CA,1.689618e+09
4,4,east london,-33.0153,27.9116,59.94,77.0,0.0,4.61,ZA,1.689618e+09

---

### Step 1: Create a map that displays a point for every city in the `city_data_df` DataFrame. The size of the point should be the humidity in each city.

In [21]:
%%capture --no-display

gmaps.configure(api_key=geoapify_key)

locations = city_data_df[["Lat", "lng"]]
humidity_weight = city_data_df["Humidity"].astype(float)

fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity_weight, max_intensity=100, point_radius=3)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Step 2: Narrow down the `city_data_df` DataFrame to find your ideal weather condition

In [22]:
# Narrow down cities that fit criteria and drop any results with null values

narrow_weather_df = city_data_df.loc[(city_data_df["Max Temp"] < 80) & (city_data_df["Max Temp"] > 70) & 
                                    (city_data_df["Wind Speed"] < 10) & (city_data_df["Cloudiness"] == 0), :]



# Drop any rows with null values

narrow_weather_df = narrow_weather_df.dropna(how='any')
# Display sample data

narrow_weather_df

,City_ID,City,Lat,lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
7,7,nahrin,36.0649,69.1334,78.60,21.0,0.0,4.05,AF,1.689618e+09
68,72,tateyama,34.9833,139.8667,76.71,84.0,0.0,3.11,JP,1.689618e+09
69,73,vila,42.0304,-8.1588,76.69,49.0,0.0,4.63,PT,1.689618e+09
125,139,angouleme,45.6500,0.1500,79.59,38.0,0.0,4.61,FR,1.689618e+09
168,185,xuchang,34.0167,113.8167,75.29,79.0,0.0,3.80,CN,1.689618e+09
194,213,hasaki,35.7333,140.8333,73.80,88.0,0.0,0.65,JP,1.689618e+09
237,261,qingdao,36.0986,120.3719,73.00,83.0,0.0,2.24,CN,1.689618e+09
239,263,central point,42.3760,-122.9164,79.65,41.0,0.0,1.99,US,1.689618e+09
360,393,iskandar,41.5539,69.7008,77.85,22.0,0.0,5.68,UZ,1.689618e+09
402,438,la ronge,55.1001,-105.2842,71.82,43.0,0.0,9.22,CA,1.689618e+09
424,462,mitchell,43.7094,-98.0298,72.73,46.0,0.0,5.75,US,1.689618e+09
429,467,ushtobe,45.2514,77.9838,78.91,23.0,0.0,9.84,KZ,1.689618e+09
466,506,marivan,35.5219,46.1760,75.36,19.0,0.0,0.87,IR,1.689618e+09
467,507,east moline,41.5009,-90.4443,76.66,56.0,0.0,7.00,US,1.689618e+09
478,518,urumqi,43.8010,87.6005,77.95,41.0,0.0,6.71,CN,1.689618e+09
525,568,tete,-16.1564,33.5867,73.49,33.0,0.0,9.22,MZ,1.689618e+09

### Step 3: Create a new DataFrame called `hotel_df`.

In [23]:
# Use the Pandas copy function to create DataFrame called hotel_df to store the city, country, coordinates, and humidity

hotel_df = narrow_weather_df

# Add an empty column, "Hotel Name," to the DataFrame so you can store the hotel found using the Geoapify API
# YOUR CODE HERE
hotel_df["Hotel Name"] = ""
hotel_df

# Display sample data
# YOUR CODE HERE

,City_ID,City,Lat,lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
7,7,nahrin,36.0649,69.1334,78.60,21.0,0.0,4.05,AF,1.689618e+09,
68,72,tateyama,34.9833,139.8667,76.71,84.0,0.0,3.11,JP,1.689618e+09,
69,73,vila,42.0304,-8.1588,76.69,49.0,0.0,4.63,PT,1.689618e+09,
125,139,angouleme,45.6500,0.1500,79.59,38.0,0.0,4.61,FR,1.689618e+09,
168,185,xuchang,34.0167,113.8167,75.29,79.0,0.0,3.80,CN,1.689618e+09,
194,213,hasaki,35.7333,140.8333,73.80,88.0,0.0,0.65,JP,1.689618e+09,
237,261,qingdao,36.0986,120.3719,73.00,83.0,0.0,2.24,CN,1.689618e+09,
239,263,central point,42.3760,-122.9164,79.65,41.0,0.0,1.99,US,1.689618e+09,
360,393,iskandar,41.5539,69.7008,77.85,22.0,0.0,5.68,UZ,1.689618e+09,
402,438,la ronge,55.1001,-105.2842,71.82,43.0,0.0,9.22,CA,1.689618e+09,
424,462,mitchell,43.7094,-98.0298,72.73,46.0,0.0,5.75,US,1.689618e+09,
429,467,ushtobe,45.2514,77.9838,78.91,23.0,0.0,9.84,KZ,1.689618e+09,
466,506,marivan,35.5219,46.1760,75.36,19.0,0.0,0.87,IR,1.689618e+09,
467,507,east moline,41.5009,-90.4443,76.66,56.0,0.0,7.00,US,1.689618e+09,
478,518,urumqi,43.8010,87.6005,77.95,41.0,0.0,6.71,CN,1.689618e+09,
525,568,tete,-16.1564,33.5867,73.49,33.0,0.0,9.22,MZ,1.689618e+09,

### Step 4: For each city, use the Geoapify API to find the first hotel located within 10,000 metres of your coordinates.

In [24]:
for index, row in hotel_df.iterrows():

    #base url
    url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    #Setting parameters with dictionary to search for hotels
    params = {"location": str(row["Lat"]) + "," +str(row["lng"]),
              "radius": str(10000),
              "type": "Hotel",
              "keyword": "Hotel",
              "key": geoapify_key}
    
    response = requests.get(url, params=params).json()
  
    try:
        hotel_df.loc[index, "Hotel Name"] = response['results'][0]['name']
        

    except (KeyError, IndexError):
        print("Missing")

Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing
Missing

In [28]:
hotel_df['Hotel Name'].replace('', np.nan, inplace=True)
hotel_df.dropna(subset=['Hotel Name'], inplace=True)
hotel_df

Empty DataFrame
Columns: [City_ID, City, Lat, lng, Max Temp, Humidity, Cloudiness, Wind Speed, Country, Date, Hotel Name]
Index: []

### Step 5: Add the hotel name and the country as additional information in the hover message for each city in the map.

In [29]:
%%capture --no-display

# Configure the map plot
# YOUR CODE HERE
locations = hotel_df[["Lat", "lng"]]
markers = gmaps.marker_layer(locations)
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=hotel_info
)

# Display the map
# YOUR CODE HERE
fig.add_layer(markers)
fig.add_layer(hotel_layer)
fig

Figure(layout=FigureLayout(height='420px'))